name: on branch update

on:
  push:
    branches:
      - main

jobs:
  ejecutar:
    runs-on: ubuntu-latest
    steps:
    - name: Chequear el código
      uses: actions/checkout@v2

    - name: Instalar dependencias
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser
        sudo apt-get install chromium-chromedriver
        pip install selenium

    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Instalar dependencias
      run: pip install -r requirements.txt
    - name: Ejecutar script
      run: python active.py
