name: on branch update

on:
  push:
    branches:
      - main

jobs:
  ejecutar:
    runs-on: ubuntu-latest
    steps:
    - name: Chequear el código
      uses: actions/checkout@v2

    - name: Instalar dependencias
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser
        sudo apt-get install chromium-chromedriver
        pip install selenium

    - name: Ejecutar el script
      run: |
        python - << EOF
        from selenium import webdriver
        
        options = webdriver.ChromeOptions()
        options.add_argument('--headless')
        options.add_argument('--no-sandbox')
        options.add_argument('--disable-dev-shm-usage')
        options.binary_location = '/usr/bin/chromium-browser'
        
        driver = webdriver.Chrome(options=options)
        driver.get("https://ipg-clone.streamlit.app/")
        print(driver.title)
        driver.quit()
        EOF
